// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: accounts/accountsapi/v1/api.proto

package accountsapiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "libs/backend/proto-gen/go/accounts/accountsapi/v1"
	v11 "libs/backend/proto-gen/go/common/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccountsAPIName is the fully-qualified name of the AccountsAPI service.
	AccountsAPIName = "accounts.accountsapi.v1.AccountsAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccountsAPIGetPersonProcedure is the fully-qualified name of the AccountsAPI's GetPerson RPC.
	AccountsAPIGetPersonProcedure = "/accounts.accountsapi.v1.AccountsAPI/GetPerson"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	accountsAPIServiceDescriptor         = v1.File_accounts_accountsapi_v1_api_proto.Services().ByName("AccountsAPI")
	accountsAPIGetPersonMethodDescriptor = accountsAPIServiceDescriptor.Methods().ByName("GetPerson")
)

// AccountsAPIClient is a client for the accounts.accountsapi.v1.AccountsAPI service.
type AccountsAPIClient interface {
	GetPerson(context.Context, *connect.Request[v11.Empty]) (*connect.Response[v1.Person], error)
}

// NewAccountsAPIClient constructs a client for the accounts.accountsapi.v1.AccountsAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccountsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccountsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &accountsAPIClient{
		getPerson: connect.NewClient[v11.Empty, v1.Person](
			httpClient,
			baseURL+AccountsAPIGetPersonProcedure,
			connect.WithSchema(accountsAPIGetPersonMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// accountsAPIClient implements AccountsAPIClient.
type accountsAPIClient struct {
	getPerson *connect.Client[v11.Empty, v1.Person]
}

// GetPerson calls accounts.accountsapi.v1.AccountsAPI.GetPerson.
func (c *accountsAPIClient) GetPerson(ctx context.Context, req *connect.Request[v11.Empty]) (*connect.Response[v1.Person], error) {
	return c.getPerson.CallUnary(ctx, req)
}

// AccountsAPIHandler is an implementation of the accounts.accountsapi.v1.AccountsAPI service.
type AccountsAPIHandler interface {
	GetPerson(context.Context, *connect.Request[v11.Empty]) (*connect.Response[v1.Person], error)
}

// NewAccountsAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccountsAPIHandler(svc AccountsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accountsAPIGetPersonHandler := connect.NewUnaryHandler(
		AccountsAPIGetPersonProcedure,
		svc.GetPerson,
		connect.WithSchema(accountsAPIGetPersonMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/accounts.accountsapi.v1.AccountsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccountsAPIGetPersonProcedure:
			accountsAPIGetPersonHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccountsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedAccountsAPIHandler struct{}

func (UnimplementedAccountsAPIHandler) GetPerson(context.Context, *connect.Request[v11.Empty]) (*connect.Response[v1.Person], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("accounts.accountsapi.v1.AccountsAPI.GetPerson is not implemented"))
}
