// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: accounts/accountsapi/v1/api.proto

package accountsapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "libs/proto-gen/go/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountsAPI_GetPerson_FullMethodName = "/accounts.accountsapi.v1.AccountsAPI/GetPerson"
)

// AccountsAPIClient is the client API for AccountsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountsAPIClient interface {
	GetPerson(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*Person, error)
}

type accountsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsAPIClient(cc grpc.ClientConnInterface) AccountsAPIClient {
	return &accountsAPIClient{cc}
}

func (c *accountsAPIClient) GetPerson(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*Person, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Person)
	err := c.cc.Invoke(ctx, AccountsAPI_GetPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsAPIServer is the server API for AccountsAPI service.
// All implementations must embed UnimplementedAccountsAPIServer
// for forward compatibility.
type AccountsAPIServer interface {
	GetPerson(context.Context, *v1.Empty) (*Person, error)
	mustEmbedUnimplementedAccountsAPIServer()
}

// UnimplementedAccountsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountsAPIServer struct{}

func (UnimplementedAccountsAPIServer) GetPerson(context.Context, *v1.Empty) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedAccountsAPIServer) mustEmbedUnimplementedAccountsAPIServer() {}
func (UnimplementedAccountsAPIServer) testEmbeddedByValue()                     {}

// UnsafeAccountsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountsAPIServer will
// result in compilation errors.
type UnsafeAccountsAPIServer interface {
	mustEmbedUnimplementedAccountsAPIServer()
}

func RegisterAccountsAPIServer(s grpc.ServiceRegistrar, srv AccountsAPIServer) {
	// If the following call pancis, it indicates UnimplementedAccountsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountsAPI_ServiceDesc, srv)
}

func _AccountsAPI_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsAPIServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountsAPI_GetPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsAPIServer).GetPerson(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountsAPI_ServiceDesc is the grpc.ServiceDesc for AccountsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.accountsapi.v1.AccountsAPI",
	HandlerType: (*AccountsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _AccountsAPI_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/accountsapi/v1/api.proto",
}
