// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: billing/paymentsapi/v1/api.proto

package paymentsapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentsAPI_GetPaymentMethod_FullMethodName = "/billing.paymentsapi.v1.PaymentsAPI/GetPaymentMethod"
)

// PaymentsAPIClient is the client API for PaymentsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentsAPIClient interface {
	GetPaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*GetPaymentMethodResponse, error)
}

type paymentsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsAPIClient(cc grpc.ClientConnInterface) PaymentsAPIClient {
	return &paymentsAPIClient{cc}
}

func (c *paymentsAPIClient) GetPaymentMethod(ctx context.Context, in *GetPaymentMethodRequest, opts ...grpc.CallOption) (*GetPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentMethodResponse)
	err := c.cc.Invoke(ctx, PaymentsAPI_GetPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsAPIServer is the server API for PaymentsAPI service.
// All implementations must embed UnimplementedPaymentsAPIServer
// for forward compatibility.
type PaymentsAPIServer interface {
	GetPaymentMethod(context.Context, *GetPaymentMethodRequest) (*GetPaymentMethodResponse, error)
	mustEmbedUnimplementedPaymentsAPIServer()
}

// UnimplementedPaymentsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentsAPIServer struct{}

func (UnimplementedPaymentsAPIServer) GetPaymentMethod(context.Context, *GetPaymentMethodRequest) (*GetPaymentMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethod not implemented")
}
func (UnimplementedPaymentsAPIServer) mustEmbedUnimplementedPaymentsAPIServer() {}
func (UnimplementedPaymentsAPIServer) testEmbeddedByValue()                     {}

// UnsafePaymentsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsAPIServer will
// result in compilation errors.
type UnsafePaymentsAPIServer interface {
	mustEmbedUnimplementedPaymentsAPIServer()
}

func RegisterPaymentsAPIServer(s grpc.ServiceRegistrar, srv PaymentsAPIServer) {
	// If the following call pancis, it indicates UnimplementedPaymentsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentsAPI_ServiceDesc, srv)
}

func _PaymentsAPI_GetPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsAPIServer).GetPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsAPI_GetPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsAPIServer).GetPaymentMethod(ctx, req.(*GetPaymentMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentsAPI_ServiceDesc is the grpc.ServiceDesc for PaymentsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.paymentsapi.v1.PaymentsAPI",
	HandlerType: (*PaymentsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentMethod",
			Handler:    _PaymentsAPI_GetPaymentMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/paymentsapi/v1/api.proto",
}
