// @generated by protoc-gen-es v2.2.2
// @generated from file common/v1/empty.proto (package common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/v1/empty.proto.
 */
export declare const file_common_v1_empty: GenFile;

/**
 * Empty represents a completely empty message
 *
 * @generated from message common.v1.Empty
 */
export declare type Empty = Message<"common.v1.Empty"> & {
};

/**
 * Describes the message common.v1.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export declare const EmptySchema: GenMessage<Empty>;

