// @generated by protoc-gen-es v2.2.2
// @generated from file common/v1/empty.proto (package common.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/v1/empty.proto.
 */
export const file_common_v1_empty = /*@__PURE__*/
  fileDesc("ChVjb21tb24vdjEvZW1wdHkucHJvdG8SCWNvbW1vbi52MSIHCgVFbXB0eUKKAQoNY29tLmNvbW1vbi52MUIKRW1wdHlQcm90b1ABWihwYWNrYWdlcy9wcm90by1nZW4vZ28vY29tbW9uL3YxO2NvbW1vbnYxogIDQ1hYqgIJQ29tbW9uLlYxygIJQ29tbW9uXFYx4gIVQ29tbW9uXFYxXEdQQk1ldGFkYXRh6gIKQ29tbW9uOjpWMWIGcHJvdG8z");

/**
 * Describes the message common.v1.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema = /*@__PURE__*/
  messageDesc(file_common_v1_empty, 0);

