package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"apps/services/accounts-graphql/internal/graph/models"
	"context"
)

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*models.Account, error) {
	return []*models.Account{
		{ID: "1", Email: "test@email.com"},
		{ID: "2", Email: "another_test@email.com"},
	}, nil
}
