// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: webhooks/inboundwebhooksapi/v1/api.proto

package inboundwebhooksapiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "libs/backend/proto-gen/go/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InboundWebhooksAuthAPI_UserRegistered_FullMethodName = "/webhooks.inboundwebhooksapi.v1.InboundWebhooksAuthAPI/UserRegistered"
)

// InboundWebhooksAuthAPIClient is the client API for InboundWebhooksAuthAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InboundWebhooksAuthAPIClient interface {
	// Auth0
	UserRegistered(ctx context.Context, in *UserRegisteredRequest, opts ...grpc.CallOption) (*v1.Empty, error)
}

type inboundWebhooksAuthAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewInboundWebhooksAuthAPIClient(cc grpc.ClientConnInterface) InboundWebhooksAuthAPIClient {
	return &inboundWebhooksAuthAPIClient{cc}
}

func (c *inboundWebhooksAuthAPIClient) UserRegistered(ctx context.Context, in *UserRegisteredRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, InboundWebhooksAuthAPI_UserRegistered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InboundWebhooksAuthAPIServer is the server API for InboundWebhooksAuthAPI service.
// All implementations must embed UnimplementedInboundWebhooksAuthAPIServer
// for forward compatibility.
type InboundWebhooksAuthAPIServer interface {
	// Auth0
	UserRegistered(context.Context, *UserRegisteredRequest) (*v1.Empty, error)
	mustEmbedUnimplementedInboundWebhooksAuthAPIServer()
}

// UnimplementedInboundWebhooksAuthAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInboundWebhooksAuthAPIServer struct{}

func (UnimplementedInboundWebhooksAuthAPIServer) UserRegistered(context.Context, *UserRegisteredRequest) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegistered not implemented")
}
func (UnimplementedInboundWebhooksAuthAPIServer) mustEmbedUnimplementedInboundWebhooksAuthAPIServer() {
}
func (UnimplementedInboundWebhooksAuthAPIServer) testEmbeddedByValue() {}

// UnsafeInboundWebhooksAuthAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InboundWebhooksAuthAPIServer will
// result in compilation errors.
type UnsafeInboundWebhooksAuthAPIServer interface {
	mustEmbedUnimplementedInboundWebhooksAuthAPIServer()
}

func RegisterInboundWebhooksAuthAPIServer(s grpc.ServiceRegistrar, srv InboundWebhooksAuthAPIServer) {
	// If the following call pancis, it indicates UnimplementedInboundWebhooksAuthAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InboundWebhooksAuthAPI_ServiceDesc, srv)
}

func _InboundWebhooksAuthAPI_UserRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InboundWebhooksAuthAPIServer).UserRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InboundWebhooksAuthAPI_UserRegistered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InboundWebhooksAuthAPIServer).UserRegistered(ctx, req.(*UserRegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InboundWebhooksAuthAPI_ServiceDesc is the grpc.ServiceDesc for InboundWebhooksAuthAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InboundWebhooksAuthAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webhooks.inboundwebhooksapi.v1.InboundWebhooksAuthAPI",
	HandlerType: (*InboundWebhooksAuthAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRegistered",
			Handler:    _InboundWebhooksAuthAPI_UserRegistered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webhooks/inboundwebhooksapi/v1/api.proto",
}
