// @generated by protoc-gen-es v2.2.2
// @generated from file accounts/accountsapi/v1/api.proto (package accounts.accountsapi.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_type_datetime } from "../../../google/type/datetime_pb";
import { file_common_v1_empty } from "../../../common/v1/empty_pb";

/**
 * Describes the file accounts/accountsapi/v1/api.proto.
 */
export const file_accounts_accountsapi_v1_api = /*@__PURE__*/
  fileDesc("CiFhY2NvdW50cy9hY2NvdW50c2FwaS92MS9hcGkucHJvdG8SF2FjY291bnRzLmFjY291bnRzYXBpLnYxIoABCgZQZXJzb24SGwoKZmlyc3RfbmFtZRgBIAEoCUIHukgEcgIQARIaCglsYXN0X25hbWUYAiABKAlCB7pIBHICEAESFAoDYWdlGAMgASgFQge6SAQaAiABEicKCGJpcnRoZGF5GAQgASgLMhUuZ29vZ2xlLnR5cGUuRGF0ZVRpbWUyUQoNQWNjb3VudHNBUElWMRJACglHZXRQZXJzb24SEC5jb21tb24udjEuRW1wdHkaHy5hY2NvdW50cy5hY2NvdW50c2FwaS52MS5QZXJzb24iAELiAQobY29tLmFjY291bnRzLmFjY291bnRzYXBpLnYxQghBcGlQcm90b1ABWjtwYWNrYWdlcy9wcm90by1nZW4vZ28vYWNjb3VudHMvYWNjb3VudHNhcGkvdjE7YWNjb3VudHNhcGl2MaICA0FBWKoCF0FjY291bnRzLkFjY291bnRzYXBpLlYxygIXQWNjb3VudHNcQWNjb3VudHNhcGlcVjHiAiNBY2NvdW50c1xBY2NvdW50c2FwaVxWMVxHUEJNZXRhZGF0YeoCGUFjY291bnRzOjpBY2NvdW50c2FwaTo6VjFiBnByb3RvMw", [file_buf_validate_validate, file_google_type_datetime, file_common_v1_empty]);

/**
 * Describes the message accounts.accountsapi.v1.Person.
 * Use `create(PersonSchema)` to create a new message.
 */
export const PersonSchema = /*@__PURE__*/
  messageDesc(file_accounts_accountsapi_v1_api, 0);

/**
 * @generated from service accounts.accountsapi.v1.AccountsAPIV1
 */
export const AccountsAPIV1 = /*@__PURE__*/
  serviceDesc(file_accounts_accountsapi_v1_api, 0);

