// @generated by protoc-gen-es v2.2.2
// @generated from file accounts/accountsapi/v1/api.proto (package accounts.accountsapi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { DateTime } from "../../../google/type/datetime_pb";
import type { EmptySchema } from "../../../common/v1/empty_pb";

/**
 * Describes the file accounts/accountsapi/v1/api.proto.
 */
export declare const file_accounts_accountsapi_v1_api: GenFile;

/**
 * @generated from message accounts.accountsapi.v1.Person
 */
export declare type Person = Message<"accounts.accountsapi.v1.Person"> & {
  /**
   * @generated from field: string first_name = 1;
   */
  firstName: string;

  /**
   * @generated from field: string last_name = 2;
   */
  lastName: string;

  /**
   * @generated from field: int32 age = 3;
   */
  age: number;

  /**
   * @generated from field: google.type.DateTime birthday = 4;
   */
  birthday?: DateTime;
};

/**
 * Describes the message accounts.accountsapi.v1.Person.
 * Use `create(PersonSchema)` to create a new message.
 */
export declare const PersonSchema: GenMessage<Person>;

/**
 * @generated from service accounts.accountsapi.v1.AccountsAPIV1
 */
export declare const AccountsAPIV1: GenService<{
  /**
   * @generated from rpc accounts.accountsapi.v1.AccountsAPIV1.GetPerson
   */
  getPerson: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof PersonSchema;
  },
}>;

