package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"apps/services/accounts-graphql/internal/graph/generated"
	"apps/services/accounts-graphql/internal/graph/models"
	"context"
	"fmt"

	"github.com/google/uuid"
)

// FindAccountByID is the resolver for the findAccountByID field.
func (r *entityResolver) FindAccountByID(ctx context.Context, id uuid.UUID) (*models.Account, error) {
	panic(fmt.Errorf("not implemented: FindAccountByID - findAccountByID"))
}

// FindViewerByID is the resolver for the findViewerByID field.
func (r *entityResolver) FindViewerByID(ctx context.Context, id uuid.UUID) (*models.Viewer, error) {
	panic(fmt.Errorf("not implemented: FindViewerByID - findViewerByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
