package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"apps/services/accounts-graphql/internal/graph/generated"
	"context"
	"fmt"
)

// Empty is the resolver for the empty field.
func (r *mutationResolver) Empty(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Empty - empty"))
}

// Empty is the resolver for the empty field.
func (r *queryResolver) Empty(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Empty - empty"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
