// @generated by protoc-gen-es v2.2.2
// @generated from file billing/paymentsapi/v1/api.proto (package billing.paymentsapi.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file billing/paymentsapi/v1/api.proto.
 */
export const file_billing_paymentsapi_v1_api = /*@__PURE__*/
  fileDesc("CiBiaWxsaW5nL3BheW1lbnRzYXBpL3YxL2FwaS5wcm90bxIWYmlsbGluZy5wYXltZW50c2FwaS52MSIlChdHZXRQYXltZW50TWV0aG9kUmVxdWVzdBIKCgJpZBgBIAEoCSItChhHZXRQYXltZW50TWV0aG9kUmVzcG9uc2USEQoJaXNQcmltYXJ5GAEgASgIMoYBCgtQYXltZW50c0FQSRJ3ChBHZXRQYXltZW50TWV0aG9kEi8uYmlsbGluZy5wYXltZW50c2FwaS52MS5HZXRQYXltZW50TWV0aG9kUmVxdWVzdBowLmJpbGxpbmcucGF5bWVudHNhcGkudjEuR2V0UGF5bWVudE1ldGhvZFJlc3BvbnNlIgBC3AEKGmNvbS5iaWxsaW5nLnBheW1lbnRzYXBpLnYxQghBcGlQcm90b1ABWjpwYWNrYWdlcy9wcm90by1nZW4vZ28vYmlsbGluZy9wYXltZW50c2FwaS92MTtwYXltZW50c2FwaXYxogIDQlBYqgIWQmlsbGluZy5QYXltZW50c2FwaS5WMcoCFkJpbGxpbmdcUGF5bWVudHNhcGlcVjHiAiJCaWxsaW5nXFBheW1lbnRzYXBpXFYxXEdQQk1ldGFkYXRh6gIYQmlsbGluZzo6UGF5bWVudHNhcGk6OlYxYgZwcm90bzM");

/**
 * Describes the message billing.paymentsapi.v1.GetPaymentMethodRequest.
 * Use `create(GetPaymentMethodRequestSchema)` to create a new message.
 */
export const GetPaymentMethodRequestSchema = /*@__PURE__*/
  messageDesc(file_billing_paymentsapi_v1_api, 0);

/**
 * Describes the message billing.paymentsapi.v1.GetPaymentMethodResponse.
 * Use `create(GetPaymentMethodResponseSchema)` to create a new message.
 */
export const GetPaymentMethodResponseSchema = /*@__PURE__*/
  messageDesc(file_billing_paymentsapi_v1_api, 1);

/**
 * @generated from service billing.paymentsapi.v1.PaymentsAPI
 */
export const PaymentsAPI = /*@__PURE__*/
  serviceDesc(file_billing_paymentsapi_v1_api, 0);

