// @generated by protoc-gen-es v2.2.2
// @generated from file billing/paymentsapi/v1/api.proto (package billing.paymentsapi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file billing/paymentsapi/v1/api.proto.
 */
export declare const file_billing_paymentsapi_v1_api: GenFile;

/**
 * @generated from message billing.paymentsapi.v1.GetPaymentMethodRequest
 */
export declare type GetPaymentMethodRequest = Message<"billing.paymentsapi.v1.GetPaymentMethodRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message billing.paymentsapi.v1.GetPaymentMethodRequest.
 * Use `create(GetPaymentMethodRequestSchema)` to create a new message.
 */
export declare const GetPaymentMethodRequestSchema: GenMessage<GetPaymentMethodRequest>;

/**
 * @generated from message billing.paymentsapi.v1.GetPaymentMethodResponse
 */
export declare type GetPaymentMethodResponse = Message<"billing.paymentsapi.v1.GetPaymentMethodResponse"> & {
  /**
   * @generated from field: bool isPrimary = 1;
   */
  isPrimary: boolean;
};

/**
 * Describes the message billing.paymentsapi.v1.GetPaymentMethodResponse.
 * Use `create(GetPaymentMethodResponseSchema)` to create a new message.
 */
export declare const GetPaymentMethodResponseSchema: GenMessage<GetPaymentMethodResponse>;

/**
 * @generated from service billing.paymentsapi.v1.PaymentsAPI
 */
export declare const PaymentsAPI: GenService<{
  /**
   * @generated from rpc billing.paymentsapi.v1.PaymentsAPI.GetPaymentMethod
   */
  getPaymentMethod: {
    methodKind: "unary";
    input: typeof GetPaymentMethodRequestSchema;
    output: typeof GetPaymentMethodResponseSchema;
  },
}>;

